/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unifae.gerenciacondominio.view;

import br.unifae.gerenciacondominio.controller.ParcelaController;
import br.unifae.gerenciacondominio.model.factory.Factory;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ManipulaParcela extends JDialog {

    private ParcelaController parcelaController;
    private Long idResidencia;
    private Long idParcela = 0L;

    /**
     * Creates new form ManipulaParcela
     */
    public ManipulaParcela(Frame owner, String title, boolean rootPaneCheckingEnabled, Connection connection, Long idResidencia) {
        super(owner, title, rootPaneCheckingEnabled);
        initComponents();
        parcelaController = new ParcelaController(connection);
        this.idResidencia = idResidencia;
    }

    public ManipulaParcela(Frame owner, String title, boolean rootPaneCheckingEnabled, Connection connection, Long idResidencia, Long idParcela) {
        super(owner, title, rootPaneCheckingEnabled);
        initComponents();
        parcelaController = new ParcelaController(connection);
        this.idResidencia = idResidencia;
        this.idParcela = idParcela;

        try {
            parcelaController.fillParcelaResidencia(idParcela, txtReceber, txtRecebido, txtDt);
        } catch (SQLException exception) {
            System.out.println("ERROA O PREENCHER INFO DA PARCELA - MSG - " + exception);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDt = new javax.swing.JFormattedTextField();
        txtRecebido = new javax.swing.JFormattedTextField();
        txtReceber = new javax.swing.JFormattedTextField();
        btnGravar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("A receber");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 30, -1, -1));

        jLabel2.setText("Recebido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 102, -1, -1));

        jLabel4.setText("Data da parcela");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        try {
            txtDt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDt.setPreferredSize(new java.awt.Dimension(64, 30));
        getContentPane().add(txtDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 90, -1));

        try {
            txtRecebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#,###.00")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, -1));

        try {
            txtReceber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#,###.00")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtReceber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, -1));

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        final String valorReceber = txtReceber.getText().replace(",", "");
        final String valorRecebidor = txtRecebido.getText().replace(",", "");
        final String dtPura = txtDt.getText().trim().replace("/", "");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        final double valorReceberFormatado = Double.parseDouble(valorReceber);
        final double valorRecebidoFormatado = Double.parseDouble(valorRecebidor);

        if (valorReceberFormatado == 0) {
            JOptionPane.showMessageDialog(rootPane, "Digite um valor valor valido para a parcela!", "Aviso!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (dtPura.isEmpty() || dtPura.length() < 8) {
            JOptionPane.showMessageDialog(rootPane, "Digite um data valida!", "Aviso!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            LocalDate data = LocalDate.parse(txtDt.getText(), formatter);

            if (idParcela == 0L) {
                parcelaController.insertParcelaResidencia(this.idResidencia, valorReceberFormatado, valorRecebidoFormatado, data);
                JOptionPane.showMessageDialog(rootPane, "Parcela cadastrada com sucesso!", "Sucesso!", JOptionPane.PLAIN_MESSAGE);

            } else {
                parcelaController.updateParcelaResidencia(this.idParcela, valorReceberFormatado, valorRecebidoFormatado, data);
                JOptionPane.showMessageDialog(rootPane, "Parcela editada com sucesso!", "Sucesso!", JOptionPane.PLAIN_MESSAGE);
            }
            this.dispose();
        } catch (SQLException exception) {
            System.out.println("ERRO AO INSERIR PARCELA - MSG - " + exception);
        }
    }//GEN-LAST:event_btnGravarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField txtDt;
    private javax.swing.JFormattedTextField txtReceber;
    private javax.swing.JFormattedTextField txtRecebido;
    // End of variables declaration//GEN-END:variables
}
