/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unifae.gerenciacondominio.view;

import br.unifae.gerenciacondominio.controller.ParcelaController;
import br.unifae.gerenciacondominio.model.DbSingleton;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ParcelasView extends javax.swing.JFrame {

    private Long idResidencia;
    private Connection connection;
    private ParcelaController controller;

    /**
     * Creates new form ParcelasView
     */
    public ParcelasView(Long idResidencia) {
        initComponents();
        this.idResidencia = idResidencia;
        txtId.setText("Residencia selecionada: " + this.idResidencia);

        try {
            connection = DbSingleton.getInstancia().getConnection();
            controller = new ParcelaController(connection);
            controller.fillTable(jTable1, idResidencia);
        } catch (SQLException exception) {
            System.out.println("ERRO AO INICIAR BANCO EM PARCELAS - msg - " + exception);
        }
    }

    public ParcelasView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtId = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Parcelas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATA", "A RECEBER", "RECEBIDO", "EM DIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Apagar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            JDialog modalDialog = new ManipulaParcela((Frame) getParent(), "Cadastrar parcela", true, this.connection, this.idResidencia);
            modalDialog.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    try {
                        controller.fillTable(jTable1, idResidencia);
                    } catch (SQLException exception) {
                        JOptionPane.showMessageDialog(rootPane, "Erro preencher tabela de parcela!", "Erro!", JOptionPane.ERROR_MESSAGE);
                        System.out.println("ERRO AO PREENCHER TABELA DE PARCELAS - MSG - " + exception);
                    }
                }
            });
            modalDialog.setSize(550, 400);
            modalDialog.setLocationRelativeTo((Frame) getParent());
            modalDialog.setVisible(true);
        } catch (Exception sQLException) {
            JOptionPane.showMessageDialog(rootPane, "Erro desconhecido ao cadastrar parcela!", "Erro!", JOptionPane.ERROR_MESSAGE);

            System.out.println("ERRO AO CADASTRAR PARCELA - " + sQLException);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        final int linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma parcela antes!", "Aviso!", JOptionPane.WARNING_MESSAGE);

            return;
        }

        final String idSelecionado = jTable1.getValueAt(linhaSelecionada, 0).toString();

        try {
            final Long idLong = Long.parseLong(idSelecionado);
            JDialog modalDialog = new ManipulaParcela((Frame) getParent(), "Editar parcela", true, this.connection, this.idResidencia, idLong);
            modalDialog.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    try {
                        controller.fillTable(jTable1, idResidencia);
                    } catch (SQLException exception) {
                        JOptionPane.showMessageDialog(rootPane, "Erro preencher tabela de parcela!", "Erro!", JOptionPane.ERROR_MESSAGE);
                        System.out.println("ERRO AO PREENCHER TABELA DE PARCELAS - MSG - " + exception);
                    }
                }
            });
            modalDialog.setSize(550, 400);
            modalDialog.setLocationRelativeTo((Frame) getParent());
            modalDialog.setVisible(true);
        } catch (Exception sQLException) {
            JOptionPane.showMessageDialog(rootPane, "Erro desconhecido ao cadastrar parcela!", "Erro!", JOptionPane.ERROR_MESSAGE);

            System.out.println("ERRO AO CADASTRAR PARCELA - " + sQLException);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        final int linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma parcela antes!", "Aviso!", JOptionPane.WARNING_MESSAGE);

            return;
        }

        final String idSelecionado = jTable1.getValueAt(linhaSelecionada, 0).toString();

        try {
            final Long idLong = Long.parseLong(idSelecionado);
            controller.deleteParcelaByIdParcela(idLong);
            controller.fillTable(jTable1, idResidencia);
            JOptionPane.showMessageDialog(rootPane, "Parcela deletada com sucesso!", "Sucesso!", JOptionPane.PLAIN_MESSAGE);
        } catch (Exception sQLException) {
            JOptionPane.showMessageDialog(rootPane, "Erro desconhecido ao apagar parcela!", "Erro!", JOptionPane.ERROR_MESSAGE);

            System.out.println("ERRO AO APAGAR PARCELA - " + sQLException);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParcelasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParcelasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParcelasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParcelasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParcelasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtId;
    // End of variables declaration//GEN-END:variables
}
